services:
  mysql:
    image: 'mysql:latest'
    env_file:
      - .env
    ports:
      - '3306:3306'
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - spring-mysql

networks:
  react-spring: {}
  spring-mysql: {}

volumes:
  db-data: {}
